// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type Account struct {
	ID         int64          `json:"id"`
	Amount     int64          `json:"amount"`
	Nonce      int64          `json:"nonce"`
	Sign       sql.NullString `json:"sign"`
	PublicKey  string         `json:"public_key"`
	PrivateKey string         `json:"private_key"`
}

type Entry struct {
	ID        int64 `json:"id"`
	AccountID int64 `json:"account_id"`
	// can be negative or positive
	Amount int64 `json:"amount"`
}

type Transfer struct {
	ID            int64 `json:"id"`
	FromAccountID int64 `json:"from_account_id"`
	ToAccountID   int64 `json:"to_account_id"`
	// must be positive
	Amount int64 `json:"amount"`
}
